/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ConsoleRouteImport } from './routes/_console'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleThreatIntelligenceRouteImport } from './routes/_console.threat-intelligence'
import { Route as ConsoleSettingsRouteImport } from './routes/_console.settings'
import { Route as ConsoleModelStatisticsRouteImport } from './routes/_console.model-statistics'
import { Route as ConsoleExplainabilityRouteImport } from './routes/_console.explainability'
import { Route as ConsoleDashboardRouteImport } from './routes/_console.dashboard'
import { Route as ConsoleAcousticAnalysisRouteImport } from './routes/_console.acoustic-analysis'
import { Route as ConsoleAboutRouteImport } from './routes/_console.about'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/_console',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleThreatIntelligenceRoute =
  ConsoleThreatIntelligenceRouteImport.update({
    id: '/threat-intelligence',
    path: '/threat-intelligence',
    getParentRoute: () => ConsoleRoute,
  } as any)
const ConsoleSettingsRoute = ConsoleSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleModelStatisticsRoute = ConsoleModelStatisticsRouteImport.update({
  id: '/model-statistics',
  path: '/model-statistics',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleExplainabilityRoute = ConsoleExplainabilityRouteImport.update({
  id: '/explainability',
  path: '/explainability',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleDashboardRoute = ConsoleDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAcousticAnalysisRoute = ConsoleAcousticAnalysisRouteImport.update({
  id: '/acoustic-analysis',
  path: '/acoustic-analysis',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAboutRoute = ConsoleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ConsoleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof ConsoleAboutRoute
  '/acoustic-analysis': typeof ConsoleAcousticAnalysisRoute
  '/dashboard': typeof ConsoleDashboardRoute
  '/explainability': typeof ConsoleExplainabilityRoute
  '/model-statistics': typeof ConsoleModelStatisticsRoute
  '/settings': typeof ConsoleSettingsRoute
  '/threat-intelligence': typeof ConsoleThreatIntelligenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof ConsoleAboutRoute
  '/acoustic-analysis': typeof ConsoleAcousticAnalysisRoute
  '/dashboard': typeof ConsoleDashboardRoute
  '/explainability': typeof ConsoleExplainabilityRoute
  '/model-statistics': typeof ConsoleModelStatisticsRoute
  '/settings': typeof ConsoleSettingsRoute
  '/threat-intelligence': typeof ConsoleThreatIntelligenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_console': typeof ConsoleRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_console/about': typeof ConsoleAboutRoute
  '/_console/acoustic-analysis': typeof ConsoleAcousticAnalysisRoute
  '/_console/dashboard': typeof ConsoleDashboardRoute
  '/_console/explainability': typeof ConsoleExplainabilityRoute
  '/_console/model-statistics': typeof ConsoleModelStatisticsRoute
  '/_console/settings': typeof ConsoleSettingsRoute
  '/_console/threat-intelligence': typeof ConsoleThreatIntelligenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/about'
    | '/acoustic-analysis'
    | '/dashboard'
    | '/explainability'
    | '/model-statistics'
    | '/settings'
    | '/threat-intelligence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/about'
    | '/acoustic-analysis'
    | '/dashboard'
    | '/explainability'
    | '/model-statistics'
    | '/settings'
    | '/threat-intelligence'
  id:
    | '__root__'
    | '/'
    | '/_console'
    | '/sitemap.xml'
    | '/_console/about'
    | '/_console/acoustic-analysis'
    | '/_console/dashboard'
    | '/_console/explainability'
    | '/_console/model-statistics'
    | '/_console/settings'
    | '/_console/threat-intelligence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console': {
      id: '/_console'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/threat-intelligence': {
      id: '/_console/threat-intelligence'
      path: '/threat-intelligence'
      fullPath: '/threat-intelligence'
      preLoaderRoute: typeof ConsoleThreatIntelligenceRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/settings': {
      id: '/_console/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ConsoleSettingsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/model-statistics': {
      id: '/_console/model-statistics'
      path: '/model-statistics'
      fullPath: '/model-statistics'
      preLoaderRoute: typeof ConsoleModelStatisticsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/explainability': {
      id: '/_console/explainability'
      path: '/explainability'
      fullPath: '/explainability'
      preLoaderRoute: typeof ConsoleExplainabilityRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/dashboard': {
      id: '/_console/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ConsoleDashboardRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/acoustic-analysis': {
      id: '/_console/acoustic-analysis'
      path: '/acoustic-analysis'
      fullPath: '/acoustic-analysis'
      preLoaderRoute: typeof ConsoleAcousticAnalysisRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/about': {
      id: '/_console/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof ConsoleAboutRouteImport
      parentRoute: typeof ConsoleRoute
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleAboutRoute: typeof ConsoleAboutRoute
  ConsoleAcousticAnalysisRoute: typeof ConsoleAcousticAnalysisRoute
  ConsoleDashboardRoute: typeof ConsoleDashboardRoute
  ConsoleExplainabilityRoute: typeof ConsoleExplainabilityRoute
  ConsoleModelStatisticsRoute: typeof ConsoleModelStatisticsRoute
  ConsoleSettingsRoute: typeof ConsoleSettingsRoute
  ConsoleThreatIntelligenceRoute: typeof ConsoleThreatIntelligenceRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleAboutRoute: ConsoleAboutRoute,
  ConsoleAcousticAnalysisRoute: ConsoleAcousticAnalysisRoute,
  ConsoleDashboardRoute: ConsoleDashboardRoute,
  ConsoleExplainabilityRoute: ConsoleExplainabilityRoute,
  ConsoleModelStatisticsRoute: ConsoleModelStatisticsRoute,
  ConsoleSettingsRoute: ConsoleSettingsRoute,
  ConsoleThreatIntelligenceRoute: ConsoleThreatIntelligenceRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
